# Generated by Django 4.2 on 2024-11-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_functionality", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="helppoint",
            name="list_object",
        ),
        migrations.AddField(
            model_name="helppoint",
            name="information",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="helppoint",
            name="name",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
