# Generated by Django 4.2 on 2024-11-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_functionality", "0002_remove_helppoint_list_object_helppoint_information_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helppoint",
            name="name",
            field=models.TextField(blank=True, default=None, null=True, unique=True),
        ),
    ]
