# Generated by Django 4.2 on 2024-12-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_functionality", "0008_section_helppoint_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
