# Generated by Django 4.2.9 on 2025-01-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_functionality", "0012_alter_helppoint_options_alter_section_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="helppoint",
            old_name="information",
            new_name="address",
        ),
        migrations.AddField(
            model_name="helppoint",
            name="link",
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="helppoint",
            name="phone",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
